# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20190401_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(verbose_name='机构描述'),
        ),
    ]
