# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20190401_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123456', max_length=20, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default=1, max_length=50, verbose_name='登录使用名'),
            preserve_default=False,
        ),
    ]
