# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='url',
            field=models.CharField(default=1, max_length=500, verbose_name='话题链接'),
            preserve_default=False,
        ),
    ]
