# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20161113_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseXuanzeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(verbose_name='所属课程')),
                ('name', models.CharField(max_length=100, verbose_name='题目名')),
                ('a', models.CharField(max_length=100, verbose_name='A')),
                ('bb', models.CharField(max_length=100, verbose_name='B')),
                ('c', models.CharField(max_length=100, verbose_name='C')),
                ('d', models.CharField(max_length=100, verbose_name='D')),
                ('answer', models.CharField(max_length=100, verbose_name='答案')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
            },
        ),
    ]
