# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_coursexuanzetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePanduanTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(verbose_name='所属课程')),
                ('name', models.CharField(max_length=100, verbose_name='题目名')),
                ('answer', models.CharField(max_length=100, verbose_name='答案')),
            ],
            options={
                'verbose_name': '判断题',
                'verbose_name_plural': '判断题',
            },
        ),
        migrations.CreateModel(
            name='CourseTiankongTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(verbose_name='所属课程')),
                ('name', models.CharField(max_length=100, verbose_name='题目')),
                ('answer', models.CharField(max_length=100, verbose_name='答案')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
            },
        ),
    ]
