# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_topic_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='话题内容'),
        ),
    ]
