# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20190403_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default=1, upload_to='topic/%Y/%m', verbose_name='话题封面'),
            preserve_default=False,
        ),
    ]
