# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_uid',
            field=models.IntegerField(default=0, verbose_name='用户'),
        ),
    ]
