# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_topic_topic_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingLunTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cengji', models.IntegerField(default=1, verbose_name='层级')),
                ('mubiao_user', models.IntegerField(default=1, verbose_name='话题所属用户')),
                ('pinglun_text', models.CharField(max_length=300, verbose_name='评论内容')),
                ('pinglun_user', models.IntegerField(verbose_name='评论者')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('pinglun_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Topic', verbose_name='所属话题')),
            ],
            options={
                'verbose_name': '话题评论',
                'verbose_name_plural': '话题评论',
            },
        ),
    ]
