# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_pingluntable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PingLunTable',
            new_name='PingLun',
        ),
    ]
