# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_pinglun_mubiao_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinglun',
            name='image',
            field=models.CharField(default='', max_length=300, verbose_name='图片路径'),
        ),
    ]
