# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_pinglun_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuiFu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cengji', models.IntegerField(verbose_name='层级')),
                ('pinglun_text', models.CharField(max_length=300, verbose_name='回复内容')),
                ('mubiao_user', models.IntegerField(verbose_name='评论所属用户')),
                ('huifu_user', models.IntegerField(verbose_name='回复者')),
                ('huifu_pinglun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.PingLun', verbose_name='所属评论')),
            ],
        ),
    ]
