# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_huifu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huifu',
            options={'verbose_name': '评论回复', 'verbose_name_plural': '评论回复'},
        ),
    ]
