# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20190407_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='huifu',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='huifu',
            name='huifu_user_name',
            field=models.CharField(default='', max_length=20, verbose_name='用户名字'),
        ),
        migrations.AddField(
            model_name='huifu',
            name='image',
            field=models.CharField(default='', max_length=300, verbose_name='图片路径'),
        ),
        migrations.AddField(
            model_name='huifu',
            name='mubiao_user_name',
            field=models.CharField(default='', max_length=20, verbose_name='被回复用户名字'),
        ),
    ]
