# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-07 23:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20190407_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuiFuHuiFu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cengji', models.IntegerField(verbose_name='层级')),
                ('text', models.CharField(max_length=300, verbose_name='回复内容')),
                ('mubiao_user', models.IntegerField(verbose_name='回复所属用户')),
                ('mubiao_user_name', models.CharField(default='', max_length=20, verbose_name='被回复用户名字')),
                ('huifu_user', models.IntegerField(verbose_name='回复者')),
                ('huifu_user_name', models.CharField(default='', max_length=20, verbose_name='回复者名字')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('image', models.CharField(default='', max_length=300, verbose_name='图片路径')),
                ('huifu_huifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.HuiFu', verbose_name='所属回复')),
            ],
            options={
                'verbose_name': '回复的回复',
                'verbose_name_plural': '回复的回复',
            },
        ),
    ]
